server:
  port: 10001

spring:
  application:
    name: aladin-mcp-server
  ai:
    mcp:
      server:
        name: aladin-mcp-server
        version: 1.0.0
        type: SYNC
        stdio: false
        enabled: true
        sse-message-endpoint: /mcp/message

aladin:
  api:
    base-url: http://www.aladin.co.kr/ttb/api
    ttb-key: # 발급 받은 ttb-key https://blog.aladin.co.kr/openapi/popup/6695306
